# Setup
remote_theme:        poole/lanyon
title:               NeuraLinux
tagline:             'Bringing AI to the Linux desktop'
description:         Linux servers have powered the AI revolution. It's time to reap the intelligence and use it on the desktop.
url:                 https://chinarjoshi.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chinar Joshi
  url:               https://github.com/chinarjoshi
  email:             chinarjoshi7@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
